language: objective-c
matrix:
    include:
        - osx_image: xcode9.3beta

script:
    - xcodebuild build -project UtsnameDemo.xcodeproj -scheme Utsname -configuration Debug -destination "platform=iOS Simulator,name=iPhone X"

